const SUBSIDIES = [
  {
    "id": "general-education-training-benefit",
    "name": "一般教育訓練給付金",
    "category": "教育訓練給付",
    "organization": "厚生労働省",
    "summary": "雇用保険加入者などが厚生労働大臣指定の教育訓練を受講・修了した場合に受講費用の一部を支給する制度。対象講座は資格・語学など幅広い。",
    "benefit_text": "受講費用の20%(上限10万円)",
    "benefit_max_yen": 100000,
    "conditions_text": "雇用保険の被保険者期間が通算3年以上(初回は1年以上)。離職後1年以内の者も対象。受講開始前3年以内に本給付金を受給していないこと。",
    "tags": {
      "employment_status": ["employee", "part_time", "unemployed_recent"],
      "purpose": ["skill_up", "career_change"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": true
    },
    "apply_url": "https://www.hellowork.mhlw.go.jp/insurance/insurance_education.html",
    "apply_method": "ハローワークで受給資格を確認し、講座修了日の翌日から1ヶ月以内に必要書類を添えてハローワークへ申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 1,
    "related_offers": ["specified-general-education-training-benefit", "specialized-practical-education-training-benefit"]
  },
  {
    "id": "specified-general-education-training-benefit",
    "name": "特定一般教育訓練給付金",
    "category": "教育訓練給付",
    "organization": "厚生労働省",
    "summary": "速やかな再就職・早期のキャリア形成に資する特定の教育訓練を対象に、一般教育訓練より高い給付率で受講費用を支援する制度。",
    "benefit_text": "受講費用の40%(上限20万円)、資格取得+就職で追加10%(上限5万円上乗せ、最大25万円)",
    "benefit_max_yen": 250000,
    "conditions_text": "雇用保険の被保険者期間が通算3年以上(初回は1年以上)。介護職員初任者研修や税理士・社労士講座等の指定講座が対象。",
    "tags": {
      "employment_status": ["employee", "part_time", "unemployed_recent"],
      "purpose": ["skill_up", "career_change"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": true
    },
    "apply_url": "https://www.hellowork.mhlw.go.jp/insurance/insurance_education.html",
    "apply_method": "ハローワークで受給資格を確認し、講座修了日の翌日から1ヶ月以内に必要書類を添えてハローワークへ申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 1,
    "related_offers": ["general-education-training-benefit", "specialized-practical-education-training-benefit"]
  },
  {
    "id": "specialized-practical-education-training-benefit",
    "name": "専門実践教育訓練給付金",
    "category": "教育訓練給付",
    "organization": "厚生労働省",
    "summary": "中長期的なキャリア形成を支援するため、看護師・介護福祉士等の専門性の高い資格取得を目指す教育訓練を対象に手厚く費用を支給する制度。",
    "benefit_text": "受講費用の50%(年間上限40万円)、資格取得等で追加給付し最大80%(年間上限64万円、最大3年で192万円)",
    "benefit_max_yen": 1920000,
    "conditions_text": "雇用保険の被保険者期間が通算3年以上(初回は2年以上)。看護師・介護福祉士・美容師等の専門職養成課程等が対象。",
    "tags": {
      "employment_status": ["employee", "part_time", "unemployed_recent"],
      "purpose": ["skill_up", "career_change"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": true
    },
    "apply_url": "https://www.hellowork.mhlw.go.jp/insurance/insurance_education.html",
    "apply_method": "受講開始前にハローワークで受給資格確認とジョブ・カード作成等のキャリアコンサルティングを受けたうえで申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 1,
    "related_offers": ["general-education-training-benefit", "specified-general-education-training-benefit"]
  },
  {
    "id": "job-seeker-support-training-benefit",
    "name": "求職者支援制度(職業訓練受講給付金)",
    "category": "求職者支援",
    "organization": "厚生労働省",
    "summary": "雇用保険を受給できないフリーランス・離職者等が無料の職業訓練を受けながら、月10万円の生活支援給付金を受け取れる制度。",
    "benefit_text": "職業訓練受講手当月10万円+通所手当(上限月42,500円)+寄宿手当(月10,700円)",
    "benefit_max_yen": 100000,
    "conditions_text": "本人月収8万円以下・世帯月収30万円以下・世帯金融資産300万円以下等の収入要件を満たし、訓練に8割以上出席すること。",
    "tags": {
      "employment_status": ["self_employed", "unemployed_recent"],
      "purpose": ["skill_up", "career_change"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyushokusha_shien/index.html",
    "apply_method": "ハローワークで求職申込・職業相談を行い、求職者支援訓練を受講しながら訓練開始後にハローワークで給付金を申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 1,
    "related_offers": []
  },
  {
    "id": "small-business-sustainability-subsidy-startup",
    "name": "小規模事業者持続化補助金<創業型>",
    "category": "創業・開業支援",
    "organization": "中小企業庁",
    "summary": "創業後1年以内の小規模事業者等が、経営計画に基づく販路開拓等の取り組みを行う際の経費の一部を補助する制度。副業の個人事業主も対象になり得る。",
    "benefit_text": "補助率2/3、補助上限200万円(インボイス特例対象は250万円)",
    "benefit_max_yen": 2500000,
    "conditions_text": "創業後1年以内(または創業予定)の小規模事業者で、特定創業支援等事業の支援を過去1年以内に受けていること等が条件。副業の場合は開業届を提出し事業所得として営んでいることが必要(雑所得扱いの副業収入は対象外)。",
    "tags": {
      "employment_status": ["self_employed"],
      "purpose": ["startup", "side_job"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.chusho.meti.go.jp/keiei/chiiki/jizokuka_sougyou/index.html",
    "apply_method": "商工会・商工会議所で事業支援計画書の発行を受けたうえで、電子申請システムJグランツ(要GビズIDプライム)から応募する。",
    "source_checked_at": "2026-07-28",
    "priority": 1,
    "related_offers": ["tokyo-startup-subsidy", "local-startup-support-subsidy"]
  },
  {
    "id": "tokyo-dx-reskilling-subsidy",
    "name": "中小企業人材スキルアップ支援事業(DXリスキリング助成金)",
    "category": "自治体リスキリング支援",
    "organization": "公益財団法人東京しごと財団(東京都)",
    "summary": "都内中小企業等が従業員にDX関連研修を受講させる際の費用を助成する東京都の制度。プログラミングやデータ分析、AI活用等の研修が対象。",
    "benefit_text": "対象経費の3/4(75%)、1人1研修上限7万5千円、1事業者あたり年間上限100万円",
    "benefit_max_yen": 1000000,
    "conditions_text": "都内に事業所を持つ中小企業等(個人事業主が営む事業所含む)が対象。ただし受講できるのは雇用する従業員のみで、個人事業主本人・法人代表者は受講対象外(事業主体としての申請は可能)。",
    "tags": {
      "employment_status": ["employee"],
      "purpose": ["skill_up", "side_job"],
      "region": ["tokyo"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.koyokankyo.shigotozaidan.or.jp/jigyo/skillup/skill-R8dx-risk.html",
    "apply_method": "東京しごと財団の公式サイトから交付申請書等をダウンロードし、研修受講前に電子申請システムで交付申請を行う。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": []
  },
  {
    "id": "osaka-skillup-support-fund",
    "name": "大阪府スキルアップ支援金",
    "category": "自治体リスキリング支援",
    "organization": "大阪府",
    "summary": "国の教育訓練給付金の対象とならない大阪府民(雇用保険未加入・加入期間1年未満等)向けに、講座の種類に応じて受講費用の50〜75%を補助する大阪府独自の制度。",
    "benefit_text": "デジタル・運輸建設関係講座は受講費用の75%(上限なし)、その他講座は50%(上限20万円)",
    "benefit_max_yen": 200000,
    "conditions_text": "大阪府内在住者で、雇用保険に加入したことがない・加入期間1年未満・離職後1年超等、国の教育訓練給付金の対象とならない方が対象(対象講座を1人1回・1講座まで利用可)。2026年4月1日以降開講、2027年2月28日までに修了する講座が対象。",
    "tags": {
      "employment_status": ["part_time", "self_employed", "unemployed_recent"],
      "purpose": ["skill_up", "career_change"],
      "region": ["osaka"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.osaka.lg.jp/o110100/koyotaisaku/skillup2/index.html",
    "apply_method": "対象講座を受講・修了後、必要書類をそろえて大阪府スキルアップ支援金事務局へ申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": ["osaka-reskilling-support-power-up"]
  },
  {
    "id": "fukuoka-digital-women-project",
    "name": "福岡県でじたる女性プロジェクト(福岡県女性デジタル人材育成・就業支援事業)",
    "category": "女性支援",
    "organization": "福岡県",
    "summary": "子育て中の女性等を対象に、オンラインでITスキル研修を無料提供し、修了後は柔軟な働き方で就労機会につなげる伴走型支援事業。",
    "benefit_text": "研修受講・利用登録ともに無料",
    "benefit_max_yen": null,
    "conditions_text": "福岡県内在住のひとり親家庭等の子育て中の女性が主な対象。ママと女性の就業支援センターへの利用登録が必要。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time", "self_employed"],
      "purpose": ["skill_up", "side_job", "career_change"],
      "region": ["fukuoka"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://digital-women.maia.co.jp/fukuoka/",
    "apply_method": "特設サイトから参加募集期間中にエントリーし、ママと女性の就業支援センターの利用登録(無料)を行う。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": []
  },
  {
    "id": "uij-turn-relocation-support",
    "name": "移住支援金(地方創生移住支援事業)",
    "category": "移住支援",
    "organization": "内閣府地方創生推進事務局・各都道府県/市町村",
    "summary": "東京圏から地方へ移住し、地域の中小企業等へ就業または起業する人に支給される支援金。副業・フリーランスとしての移住起業も対象になり得る。",
    "benefit_text": "世帯最大100万円、単身最大60万円(起業支援金と併用で最大300万円)",
    "benefit_max_yen": 1000000,
    "conditions_text": "東京23区在住または通勤していた人が対象地域へ移住し、マッチングサイト掲載の中小企業等への就業や起業をすること等が条件。",
    "tags": {
      "employment_status": ["employee", "self_employed", "unemployed_recent"],
      "purpose": ["career_change", "startup"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.chisou.go.jp/sousei/ijyu_shienkin.html",
    "apply_method": "移住先の都道府県・市区町村の相談窓口へ問い合わせ、移住後に必要書類を添えて自治体へ申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": ["local-startup-support-subsidy"]
  },
  {
    "id": "local-startup-support-subsidy",
    "name": "起業支援金(地方創生起業支援事業)",
    "category": "創業・開業支援",
    "organization": "内閣府地方創生推進事務局・各都道府県",
    "summary": "地域の課題解決に資する社会的事業での起業を支援する制度。移住を伴わなくても利用可能な場合があり、移住支援金と併用で増額される。",
    "benefit_text": "起業経費の1/2以内、上限200万円(移住支援金と併用で最大300万円)",
    "benefit_max_yen": 2000000,
    "conditions_text": "都道府県が策定する地域課題解決型の社会的事業分野で法人設立・個人事業開業をすること。実施都道府県により対象要件が異なる。",
    "tags": {
      "employment_status": ["self_employed", "employee", "unemployed_recent"],
      "purpose": ["startup", "side_job"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.chisou.go.jp/sousei/shienkin_index.html",
    "apply_method": "事業を実施する都道府県の窓口で事業計画の審査を受け、採択後に法人設立・開業して交付申請を行う。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": ["uij-turn-relocation-support", "small-business-sustainability-subsidy-startup"]
  },
  {
    "id": "single-parent-education-training-benefit",
    "name": "ひとり親家庭自立支援教育訓練給付金",
    "category": "ひとり親支援",
    "organization": "こども家庭庁・各都道府県/市区町村",
    "summary": "ひとり親家庭の父母が就業に資する教育訓練を受講・修了した場合に受講費用の一部を支給し、経済的自立を後押しする制度。",
    "benefit_text": "受講費用の60%(下限1万2,001円、上限20万円、専門実践教育訓練は最大160万円)",
    "benefit_max_yen": 1600000,
    "conditions_text": "児童扶養手当受給者またはこれと同等の所得水準にあるひとり親家庭の父母で、対象教育訓練の必要性が認められること。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time", "self_employed"],
      "purpose": ["skill_up", "career_change"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.cfa.go.jp/policies/hitori-oya/syokugyou-kunren",
    "apply_method": "居住する市区町村(福祉事務所等)へ事前相談し、講座受講前に対象講座の指定確認を受けたうえで修了後に申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": ["single-parent-vocational-training-promotion-benefit"]
  },
  {
    "id": "single-parent-vocational-training-promotion-benefit",
    "name": "ひとり親家庭高等職業訓練促進給付金",
    "category": "ひとり親支援",
    "organization": "こども家庭庁・各都道府県/市区町村",
    "summary": "看護師・介護福祉士等の資格取得を目指し養成機関で修業するひとり親に対し、修業期間中の生活費を給付する制度。",
    "benefit_text": "月額10万円(住民税課税世帯は月額7万500円)、修了後さらに5万円を追加支給",
    "benefit_max_yen": 100000,
    "conditions_text": "児童扶養手当受給水準の所得のひとり親家庭の父母で、6ヶ月以上の養成機関修業により対象資格取得が見込まれること。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time"],
      "purpose": ["career_change", "skill_up"],
      "region": ["nationwide"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.cfa.go.jp/policies/hitori-oya/syokugyou-kunren",
    "apply_method": "居住する市区町村の窓口へ事前相談し、養成機関入学前に対象資格・機関の確認を受けたうえで申請する。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": ["single-parent-education-training-benefit"]
  },
  {
    "id": "tokyo-women-reemployment-support-program",
    "name": "わたしの再就職応援プログラム(女性しごと応援テラス)",
    "category": "女性支援",
    "organization": "公益財団法人東京しごと財団(東京しごとセンター)",
    "summary": "結婚・出産・育児・介護等で離職した女性向けに、キャリアカウンセリングやパソコン実習・職種別実習、職場体験を無料で提供する再就職支援プログラム。",
    "benefit_text": "全プログラム無料(個別相談は何度でも無料)",
    "benefit_max_yen": null,
    "conditions_text": "東京都内在住・在勤で再就職を目指す女性(ブランクのある方等)が対象。年齢や雇用形態を問わず利用可能。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time"],
      "purpose": ["career_change", "skill_up"],
      "region": ["tokyo"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.tokyoshigoto.jp/facility/1f/women/",
    "apply_method": "東京しごとセンター(女性しごと応援テラス)の窓口またはウェブサイトから利用登録・予約をして相談やセミナーに参加する。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": []
  },
  {
    "id": "tokyo-startup-subsidy",
    "name": "創業助成事業(東京都創業助成金)",
    "category": "創業・開業支援",
    "organization": "公益財団法人東京都中小企業振興公社(東京都)",
    "summary": "都内での創業を計画する個人や創業5年未満の中小企業者等に対し、賃借料・広告費・人件費等の経費の一部を助成する制度。",
    "benefit_text": "助成対象経費の2/3以内、上限400万円(下限100万円)",
    "benefit_max_yen": 4000000,
    "conditions_text": "都内で創業予定または創業後5年未満で、TOKYO創業ステーションのプランコンサルティング等の指定創業支援事業を利用済みであること。",
    "tags": {
      "employment_status": ["self_employed", "employee"],
      "purpose": ["startup", "side_job"],
      "region": ["tokyo"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.tokyo-sogyo-net.metro.tokyo.lg.jp/finance/sogyo_josei.html",
    "apply_method": "TOKYO創業ステーション等の指定支援事業を利用後、募集期間中に東京都中小企業振興公社へ交付申請書を提出する。",
    "source_checked_at": "2026-07-28",
    "priority": 2,
    "related_offers": ["small-business-sustainability-subsidy-startup"]
  },
  {
    "id": "tokyo-women-startup-vc-support",
    "name": "東京都スタートアップ・エコシステムにおける女性活躍推進事業",
    "category": "女性支援",
    "organization": "東京都",
    "summary": "女性起業家を対象に、資金調達支援や事業計画策定支援など、起業初期段階に必要なサポートを一体的に提供する東京都の事業。",
    "benefit_text": "個別相談・支援は原則無料、資金調達(VC等)とのマッチング支援を含む",
    "benefit_max_yen": null,
    "conditions_text": "都内で起業を目指す・起業して間もない女性起業家が対象。事業計画の内容により支援メニューが異なる。",
    "tags": {
      "employment_status": ["self_employed", "employee", "unemployed_recent"],
      "purpose": ["startup", "side_job"],
      "region": ["tokyo"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://women-startup-vc.metro.tokyo.lg.jp/",
    "apply_method": "公式サイトで事業内容を確認し、申込フォームまたは相談窓口経由でエントリーする。",
    "source_checked_at": "2026-07-28",
    "priority": 3,
    "related_offers": ["tokyo-startup-subsidy"]
  },
  {
    "id": "osaka-reskilling-support-power-up",
    "name": "リスキリングサポートパワーアップ事業",
    "category": "自治体リスキリング支援",
    "organization": "大阪府(受託:株式会社ワークアカデミー)",
    "summary": "求職者・在職者向けにキャリアコンサルタントによるマンツーマン相談やオンラインセミナーを無料提供し、リスキリングによるキャリアアップを後押しする大阪府の事業。",
    "benefit_text": "相談・セミナー全て無料(オンライン・対面・AIチャットボット対応)",
    "benefit_max_yen": null,
    "conditions_text": "インターネット環境とZoomが利用できる求職者・在職中の労働者が対象。OSAKAしごとフィールドへの登録が必要な場合がある。",
    "tags": {
      "employment_status": ["employee", "part_time", "unemployed_recent", "self_employed"],
      "purpose": ["skill_up", "career_change"],
      "region": ["osaka"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://reskilling.shigotofield.jp/",
    "apply_method": "公式サイトの予約フォームからオンライン相談・セミナーを予約するか、対面相談デスクへ予約なしで来場する。",
    "source_checked_at": "2026-07-28",
    "priority": 3,
    "related_offers": ["osaka-skillup-support-fund"]
  },
  {
    "id": "fukuoka-professional-jinzai-matching",
    "name": "福岡県プロフェッショナル人材センター(副業・兼業人材マッチング支援)",
    "category": "自治体リスキリング支援",
    "organization": "福岡県プロフェッショナル人材センター(内閣府事業)",
    "summary": "福岡県内中小企業の経営課題解決のため、都市部人材等の副業・兼業を含むプロフェッショナル人材の活用をコーディネートする相談窓口。",
    "benefit_text": "相談・マッチング支援は無料",
    "benefit_max_yen": null,
    "conditions_text": "副業・兼業で福岡県内企業を支援したい人材、および人材活用を検討する福岡県内中小企業が対象。",
    "tags": {
      "employment_status": ["employee", "self_employed"],
      "purpose": ["side_job", "career_change"],
      "region": ["fukuoka"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.projinzai-fukuoka.jp/",
    "apply_method": "公式サイトまたは電話・メールでセンターに相談を申し込み、副業・兼業案件のマッチングを受ける。",
    "source_checked_at": "2026-07-28",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "manabi-dx-women-recommended-courses",
    "name": "マナビDX「特に女性におすすめ」講座(受講料支援講座含む)",
    "category": "女性支援",
    "organization": "経済産業省・独立行政法人情報処理推進機構(IPA)",
    "summary": "経済産業省とIPAが運営するデジタル人材育成ポータルで、多様な働き方に活かせる女性向け講座を紹介し、一部講座は受講料支援や無償受講も可能。",
    "benefit_text": "サイト利用・会員登録不要で無料、一部講座は無料または受講料の補助あり(詳細は要確認)",
    "benefit_max_yen": null,
    "conditions_text": "特定の年齢・雇用形態要件はなく、デジタルスキルを学びたい女性であれば誰でも講座を検索・受講可能。",
    "tags": {
      "employment_status": [],
      "purpose": ["skill_up", "side_job", "career_change"],
      "region": ["nationwide"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://manabi-dx.ipa.go.jp/",
    "apply_method": "マナビDXサイトで「特に女性におすすめ」カテゴリから講座を検索し、各講座提供事業者のページから直接申し込む。",
    "source_checked_at": "2026-07-28",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "kanagawa-dx-reskilling-jinzai-ikusei",
    "name": "神奈川県リスキリング人材育成事業",
    "category": "自治体リスキリング支援",
    "organization": "神奈川県産業労働局",
    "summary": "県内中小企業がDX戦略・IT環境整備・業務効率化等5コースから選び、診断・オンライン学習・伴走支援を通じ従業員のリスキリングを無料で行える神奈川県の事業。",
    "benefit_text": "受講費用無料(1社最大3名まで)",
    "benefit_max_yen": null,
    "conditions_text": "神奈川県内に本社・事業所を持つ中小企業等(みなし大企業除く)が対象。書類選考制で例年5〜6月頃募集、採用は約150社程度。",
    "tags": {
      "employment_status": ["employee"],
      "purpose": ["skill_up"],
      "region": ["kanagawa"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.kanagawa.jp/osirase/0606/dx-reskilling/index.html",
    "apply_method": "公式サイトから募集要項を確認し、企業単位で応募書類を提出。書類選考を経て採択企業が受講を開始する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "kanagawa-women-career-counseling",
    "name": "かながわ女性キャリアカウンセリング相談室",
    "category": "女性支援",
    "organization": "神奈川県(マザーズハローワーク横浜内)",
    "summary": "再就職・転職を目指す女性向けに女性カウンセラーによる個別キャリアカウンセリングを無料で提供する神奈川県の相談窓口。厚木市・平塚市への出張相談もある。",
    "benefit_text": "相談・カウンセリングは無料",
    "benefit_max_yen": null,
    "conditions_text": "これから働きたい・再就職や転職を考えている女性が対象。月〜木曜はキャリア相談、第1・3金曜は女性職員、第4金曜は女性弁護士による労働相談も実施。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time"],
      "purpose": ["career_change", "skill_up"],
      "region": ["kanagawa"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.kanagawa.jp/docs/z4r/josei/career.html",
    "apply_method": "電話等で事前予約のうえ、マザーズハローワーク横浜内の相談室を利用する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "aichi-startup-subsidy",
    "name": "あいちスタートアップ創業支援事業費補助金",
    "category": "創業・開業支援",
    "organization": "愛知県(事務局:株式会社ツクリエ)",
    "summary": "愛知県内で新技術活用や地域課題解決を目指す起業者・第二創業者・事業承継者に対し、補助金と伴走支援(メンタリング等)を一体で提供する制度。",
    "benefit_text": "補助対象経費の1/2以内(上限200万円、下限25万円)",
    "benefit_max_yen": 2000000,
    "conditions_text": "県内で開業登記する個人事業主・法人代表者で、デジタル技術活用による新市場開拓や地域課題解決を目指す事業計画を持つこと。",
    "tags": {
      "employment_status": ["self_employed"],
      "purpose": ["startup"],
      "region": ["aichi"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.aichi.jp/press-release/startup-hojokin2025.html",
    "apply_method": "電子申請システムで交付申請書・事業計画書等の必要書類を提出し、審査を経て採択される。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": ["tokyo-startup-subsidy", "small-business-sustainability-subsidy-startup"]
  },
  {
    "id": "aichi-women-reemployment-support",
    "name": "あいち子育て女性再就職サポートセンター(ママ・ジョブ・あいち)",
    "category": "女性支援",
    "organization": "愛知県労働局労働福祉課(運営:公益財団法人愛知県労働協会)",
    "summary": "出産・育児等で離職し再就職を目指す女性向けに、相談・カウンセリング、職場復帰セミナー、就職説明会、職場実習・見学会を無料で提供する愛知県の支援拠点。",
    "benefit_text": "相談・セミナー・実習はすべて無料",
    "benefit_max_yen": null,
    "conditions_text": "出産・育児等で離職し再び働きたい女性、継続就労に不安を感じる女性が対象。窓口・電話・オンラインで相談可能、託児利用も可(要事前予約)。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time"],
      "purpose": ["career_change", "skill_up"],
      "region": ["aichi"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://famifure.pref.aichi.jp/womens-support/",
    "apply_method": "電話・メール・FAX・窓口で相談を予約し、カウンセリングやセミナーを利用する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "saitama-women-digital-jinzai-training",
    "name": "女性のデジタル人材育成講座(埼玉県女性キャリアセンター)",
    "category": "女性支援",
    "organization": "埼玉県女性キャリアセンター",
    "summary": "出産・子育て等で離職した女性等を対象に、WEBクリエイターコース等のデジタルスキルをオンラインで無料習得できる埼玉県の講座。在職中の受講も可能。",
    "benefit_text": "受講無料(通信費は自己負担)",
    "benefit_max_yen": null,
    "conditions_text": "埼玉県内在住または県内就業希望の女性が対象。毎月開講され各月1,000名程度募集している。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time", "employee"],
      "purpose": ["skill_up", "side_job", "career_change"],
      "region": ["saitama"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.saitama.lg.jp/a0816/library-info/2025080101.html",
    "apply_method": "埼玉県女性キャリアセンター(電話048-601-5810)へ問い合わせ、開講月ごとの募集に申し込む。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "saitama-startup-social-challenge-program",
    "name": "社会課題解決型創業支援プログラム(創業・ベンチャー支援センター埼玉)",
    "category": "創業・開業支援",
    "organization": "公益財団法人埼玉県産業振興公社(創業・ベンチャー支援センター埼玉)",
    "summary": "社会課題の解決につながる創業を目指す起業希望者に対し、中小企業診断士等のアドバイザーと先輩起業家が伴走支援するとともに創業経費の一部を補助するプログラム。",
    "benefit_text": "創業経費の1/2以内、最大100万円",
    "benefit_max_yen": 1000000,
    "conditions_text": "社会課題解決型の事業での創業を目指す個人・団体が対象(支援対象は例年10者程度)。詳細な居住地・業種要件は要問合せ。",
    "tags": {
      "employment_status": ["self_employed", "employee", "unemployed_recent"],
      "purpose": ["startup"],
      "region": ["saitama"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.saitama.lg.jp/a0803/sspj/syakaikadai_kanendo.html",
    "apply_method": "創業・ベンチャー支援センター埼玉へ相談のうえ、募集要項に従い応募書類を提出する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "chiba-startup-support-subsidy",
    "name": "ちば創業応援助成金",
    "category": "創業・開業支援",
    "organization": "公益財団法人千葉県産業振興センター",
    "summary": "先進的アイデアの事業化や地域課題解決型の創業を目指す個人・事業者を対象に、創業経費の一部を助成する千葉県の制度。",
    "benefit_text": "対象経費の1/2以内、上限100万円",
    "benefit_max_yen": 1000000,
    "conditions_text": "千葉県内で創業予定または創業5年未満で、市町村の特定創業支援事業修了証明書取得者または県内公的インキュベーション施設入居者のいずれかに該当すること。",
    "tags": {
      "employment_status": ["self_employed", "employee"],
      "purpose": ["startup"],
      "region": ["chiba"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.ccjc-net.or.jp/contents_detail.php?frmId=3636",
    "apply_method": "受付審査後、外部委員によるプレゼンテーション審査を経て採択が決定する(例年4月頃募集)。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "chiba-job-support-center",
    "name": "千葉県ジョブサポートセンター(ジョブサポちば)",
    "category": "求職者支援",
    "organization": "千葉県商工労働部雇用労働課(ハローワークと連携運営)",
    "summary": "生活相談から職業相談・職業紹介までをワンストップで提供する千葉県の就労支援窓口。子育て中の女性や中高年齢者向けサービスを重点的に実施している。",
    "benefit_text": "相談・職業紹介は無料",
    "benefit_max_yen": null,
    "conditions_text": "求職者、在職中で転職を考えている人が対象。平日9-17時に加え第1・3・5土曜、火・木の夜間(17-20時)も利用可(要予約)。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time", "employee"],
      "purpose": ["career_change", "skill_up"],
      "region": ["chiba"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.chiba.lg.jp/koyou/chuukonen/jobsupport.html",
    "apply_method": "電話等で事前予約のうえジョブサポちばの窓口を利用する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "hokkaido-startup-promotion-subsidy",
    "name": "創業促進支援事業",
    "category": "創業・開業支援",
    "organization": "公益財団法人北海道中小企業総合支援センター",
    "summary": "道内に主たる事務所を設けて新規に事業を開始する個人・中小企業者の事業展開経費の一部を助成する北海道の制度。",
    "benefit_text": "対象経費の1/2以内、上限100万円",
    "benefit_max_yen": 1000000,
    "conditions_text": "道内で事務所を設置して創業する個人・中小企業者が対象。対象経費は原材料費・広告宣伝費・出展料等(公募ごとに募集要項が変わるため要確認)。",
    "tags": {
      "employment_status": ["self_employed", "employee"],
      "purpose": ["startup"],
      "region": ["hokkaido"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.hsc.or.jp/consul/foundation/",
    "apply_method": "直近の公募要項を確認のうえ北海道中小企業総合支援センターへ申請書類を提出する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "hokkaido-professional-jinzai-matching",
    "name": "北海道プロフェッショナル人材センター(副業・兼業人材マッチング支援)",
    "category": "自治体リスキリング支援",
    "organization": "公益財団法人北海道中小企業総合支援センター(北海道委託事業)",
    "summary": "道内中小企業の経営課題解決のため、道外プロ人材の副業・兼業(業務委託契約)を含むマッチングを無料でコーディネートする北海道の相談窓口。",
    "benefit_text": "相談・マッチング支援は無料",
    "benefit_max_yen": null,
    "conditions_text": "副業・兼業で道内企業を支援したい人材、および人材活用を検討する道内中小企業が対象。",
    "tags": {
      "employment_status": ["employee", "self_employed"],
      "purpose": ["side_job", "career_change"],
      "region": ["hokkaido"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://pro-jinzai-hokkaido.jp/",
    "apply_method": "電話等でセンターに相談を申し込み、副業・兼業案件のマッチングを受ける。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": ["fukuoka-professional-jinzai-matching"]
  },
  {
    "id": "hyogo-startup-support-subsidy",
    "name": "起業家支援事業(一般事業枠)",
    "category": "創業・開業支援",
    "organization": "公益財団法人ひょうご産業活性化センター",
    "summary": "兵庫県内での起業・第二創業にかかる経費の一部を助成する制度。空き家を活用した起業の場合は助成上限が引き上げられる。",
    "benefit_text": "助成対象経費の1/2以内、上限100万円(空き家活用時は上限200万円)",
    "benefit_max_yen": 2000000,
    "conditions_text": "兵庫県内在住または居住予定で、県内で起業・第二創業を行う(予定を含む)こと。同センターの過去受給者は対象外。",
    "tags": {
      "employment_status": ["self_employed", "employee"],
      "purpose": ["startup"],
      "region": ["hyogo"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://web.hyogo-iic.ne.jp/shinjigyo/kigyoka",
    "apply_method": "商工会・商工会議所またはよろず支援拠点で事前相談後、オンラインフォームで応募し書面を提出する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "hyogo-women-challenge-counseling",
    "name": "女性のためのチャレンジ相談(女性就業相談室・イーブン)",
    "category": "女性支援",
    "organization": "兵庫県立男女共同参画センター・イーブン",
    "summary": "再就職・起業・在宅ワーク等を考える女性向けに、社会保険労務士やキャリアコンサルタントによる個別相談やパソコン講座・セミナーを無料で提供する兵庫県の支援拠点。",
    "benefit_text": "相談・講座・一時保育は原則無料",
    "benefit_max_yen": null,
    "conditions_text": "再就職・起業・在宅ワーク等を考えたい女性が対象。原則毎月第1〜第4木曜日に対面・オンライン・電話で相談できる。",
    "tags": {
      "employment_status": ["unemployed_recent", "part_time", "self_employed"],
      "purpose": ["career_change", "startup", "skill_up"],
      "region": ["hyogo"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://hyogo-even.jp/joseishugyou",
    "apply_method": "予約専用電話(078-360-8554)で申し込み、対面・オンライン・電話のいずれかで相談を受ける。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "miyagi-startup-acceleration-subsidy",
    "name": "宮城県スタートアップ加速化支援事業",
    "category": "創業・開業支援",
    "organization": "公益財団法人みやぎ産業振興機構",
    "summary": "地域課題解決に資する事業での創業・第二創業・事業承継型創業を目指す中小企業者等を支援する宮城県の補助金。デジタル活用・DX推進枠は補助率・上限額が優遇される。",
    "benefit_text": "一般枠は対象経費の1/2以内(上限100万円)、デジタル活用・DX推進枠は対象経費の2/3以内(上限250万円)",
    "benefit_max_yen": 2500000,
    "conditions_text": "宮城県内に本社・本店を置き、募集開始から6ヶ月以内に創業予定、または開始前1年以内に創業した事業者等が対象。女性起業家・事業承継型創業は加点措置がある。",
    "tags": {
      "employment_status": ["self_employed", "employee"],
      "purpose": ["startup"],
      "region": ["miyagi"],
      "gender": ["any"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.joho-miyagi.or.jp/business-menu/startup",
    "apply_method": "事前に電話・メールで相談のうえ申請書類を作成し、募集期間中にみやぎ産業振興機構へ持参提出する。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  },
  {
    "id": "miyagi-women-career-restart-support",
    "name": "みやぎ女性のキャリア・リスタート支援センター",
    "category": "女性支援",
    "organization": "宮城県(みやぎジョブカフェ内)",
    "summary": "子育て・介護・不妊治療等で離職した女性の再就職を支援する宮城県の拠点。専属キャリアコンサルタントによる個別カウンセリングやセミナーを無料で提供する。",
    "benefit_text": "カウンセリング・セミナーはすべて無料",
    "benefit_max_yen": null,
    "conditions_text": "家庭の事情等により現在無職の女性が対象。平日火〜金曜に対面・オンラインで利用可能、参加中の一時保育支援制度もある。",
    "tags": {
      "employment_status": ["unemployed_recent"],
      "purpose": ["career_change", "skill_up"],
      "region": ["miyagi"],
      "gender": ["female"],
      "age_range": [null, null],
      "requires_employment_insurance": false
    },
    "apply_url": "https://www.pref.miyagi.jp/soshiki/koyou/josei_career.html",
    "apply_method": "平日火〜金10:00〜18:00に対面またはオンラインで予約し、1回90〜120分程度のカウンセリングを受ける。",
    "source_checked_at": "2026-07-29",
    "priority": 3,
    "related_offers": []
  }
]
;
